name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Apt Update
      run: apt-get update
    
    - name: Install library dependencies
      run: apt-get install -y libtagc0 libmp3lame0 libsndfile1
    
    - name: Raku version
      run: raku -v

    - name: Update Zef
      run:  zef install --force-install https://github.com/ugexe/zef.git

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Run tests
      run: zef test -v --debug .
